#!/bin/bash
#SBATCH --job-name 1.dft.g09
#SBATCH --time=40000
#SBATCH --nodes=1
#SBATCH --mem=4G
#SBATCH --cpus-per-task=1
#SBATCH --partition=mei2_medmem
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=ym95
#SBATCH --ntasks-per-node=8
g09 1.com
