#!/bin/bash
#SBATCH --job-name 1.losc
#SBATCH --time=40000
#SBATCH --nodes=1
#SBATCH --mem=4G
#SBATCH --cpus-per-task=1
#SBATCH --partition=mei2_medmem
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=ym95
qm4d_git 1.inp > 1.out
