#!/bin/bash
#SBATCH --job-name 1.dft.b3lyp
#SBATCH --time=100
#SBATCH --nodes=1
#SBATCH --ntasks=8
#SBATCH --mem=1G
#SBATCH --partition=mei3_debug
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=ym95
export OMP_NUM_THREADS=8
qm4d_omp 1.inp > 1.8.out.out
